### ISSUE TITLE
Build examples in CI

### ISSUE THREAD

**Issue by remcohaszing** [motifland/markprompt-js#16]
**Is your feature request related to a problem? Please describe.**
Examples may break, even though linting succeeds.

**Describe the solution you'd like**
Build all examples.

**Describe alternatives you've considered**
They could be end-to-end tested, though that might be a bit much for an example.

**Additional context**
Currently we have the `with-css-modules` example, but #13 also adds `with-docusaurus`.

**Comment by nickrttn** [comment]
Fixed by b26c8d96c35b95ec712e654dc156d5462353a2a7
