### ISSUE TITLE
Script tag fails with `Unexpected token 'export'`

### ISSUE THREAD

**Issue by michaelfester** [motifland/markprompt-js#167]
**Describe the bug**
Script tag throws an `Unexpected token 'export'` error.

**To Reproduce**

From John on Discord ([reference](https://discord.com/channels/937351648559378463/937353172148707338/1147989123752263751)):

When I add it to web page (as described in docs), it does not work. In DevTools console I see Uncaught SyntaxError: Unexpected token 'export'
I am able to fix this error adding type="module" script attribute. But apparently it is not enough.

**Comment by nickrttn** [comment]
Closed with #170
