### ISSUE TITLE
Unable to process uploaded files

### ISSUE THREAD

**Issue by johnd0e** [motifland/markprompt-js#180]
**Describe the bug**

Uploaded files are not processed

**To Reproduce**

1. Go to Data tab and upload a bunch of *.txt files (see: "21 files added")
2. Click on 'Start Training' and see 'Processing Complete'
3. Notice that there still stated '0 files indexed' 
4. Go to Playground and see "Great! Now hit 'Process sources'" message
5. Click 'Process sources', see 'Done processing sources' message.
6. See that nothing changed: Playground is not accessible.

**Comment by johnd0e** [comment]
Ok, the problem is that my files have `.text` extension.

**Comment by michaelfester** [comment]
Yes, `.txt` will work however.

**Comment by johnd0e** [comment]
Ok, but it is still desirable to get more meaningful error message.
Or even better: allow custom extensions.
