### ISSUE TITLE
Display appropriate error message when API is down

### ISSUE THREAD

**Issue by michaelfester** [motifland/markprompt-js#226]
**Is your feature request related to a problem? Please describe.**
The OpenAI API has been down today. Currently, the response is the generic one, namely "Sorry, I am not sure how to answer that". In case of server downtime, we should indicate that do that users don't get the impression that the chatbot doesn't know the answer. Here is how it shows up in the Supabase chatbot, for inspiration:

<img width="920" alt="CleanShot 2023-10-19 at 17 42 12@2x" src="https://github.com/motifland/markprompt-js/assets/504893/d6b478ad-9ec3-424e-ba20-4e04cc36165a">

**Comment by nickrttn** [comment]
Closed in #240
