### ISSUE TITLE
Automatically indicate in the prompt when OpenAI/Supabase is down

### ISSUE THREAD

**Issue by schneegansm** [motifland/markprompt-js#239]
OpenAI was down yesterday and it would be helpful for the end user to know that Markprompt is not answering the question because OpenAI is down.

<sub>From [SyncLinear.com](https://synclinear.com) | [MOT-127](https://linear.app/motifland/issue/MOT-127/automatically-indicate-in-the-prompt-when-openai-is-down)</sub>

**Comment by michaelfester** [comment]
@nickrttn I believe this one can be closed?

**Comment by nickrttn** [comment]
Fixed by #240
