### ISSUE TITLE
References container cause container container to stretch

### ISSUE THREAD

**Issue by michaelfester** [motifland/markprompt-js#29]
**Describe the bug**
In the vanilla JS component, if references overflow, the container div stretches outside its boundaries. It might also be the case for the headless React version (need to check that the generated CSS works as expected).

**To Reproduce**

1. Enter a query that contains enough references to overflow the container (or alternatively, edit the DOM in the browser dev console)
2. The references makes the container div stretch outside its boundaries:

![image](https://github.com/motifland/markprompt-js/assets/504893/466e29c5-1c34-4736-82b4-ebd2e0949a62)

**Expected behavior**
The references list should scroll horizontally and not cause the container div to stretch.

**Comment by nickrttn** [comment]
Fixed by #34
